package de.tub.citydb.db.xlink.importer;

public enum DBXlinkImporterEnum {
	LINEAR_RING,
	SURFACE_GEOMETRY,
	XLINK_BASIC,
	XLINK_TEXTUREPARAM,
	XLINK_TEXTUREASSOCIATION,
	EXTERNAL_FILE,
	XLINK_DEPRECATED_MATERIAL,
	GROUP_TO_CITYOBJECT
}
