<?xml version="1.0" encoding="utf-8"?><!-- Generated by:                                    -->
<!-- IFC -> cityGML Converter                         -->
<!-- (C) - Institute for Applied Computer Science     -->
<!-- Forschungszentrum Karlsruhe                      -->
<!-- Not for commercial use                           -->
<!-- Generated by: IfcExplorer-->
<!-- cityGML Schema: 1.0.0                            -->
<!-- Level of Detail 1--><!-- Creation Date: Tuesday, 23 November 2010 - 10:37:59-->
<!-- Edited Manually in Oxygen 8.2 -->
<!-- Modified by GMLOffset.xslt at Mon Dec 6 2010 -->
<!-- Version 2 Building located in the area of KIT Campus North)-->
<core:CityModel xsi:schemaLocation="http://www.opengis.net/citygml/1.0 ../../../%5BCityGML-Schemata%5D/Schema_CityGML_1_0/CityGML.xsd" xmlns:core="http://www.opengis.net/citygml/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:water="http://www.opengis.net/citygml/waterbody/1.0" xmlns:app="http://www.opengis.net/citygml/appearance/1.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:sub="http://www.opengis.net/ade/sub" xmlns:genobj="http://www.opengis.net/citygml/generics/1.0" xmlns:trpt="http://www.opengis.net/citygml/transportation/1.0" xmlns:veget="http://www.opengis.net/citygml/vegetation/1.0" xmlns:noise="http://www.citygml.org/ade/noise_de" xmlns:relief="http://www.opengis.net/citygml/relief/1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:texsurf="http://www.opengis.net/citygml/texturedsurface/1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:landuse="http://www.opengis.net/citygml/landuse/1.0" xmlns:group="http://www.opengis.net/citygml/cityobjectgroup/1.0" xmlns:furnit="http://www.opengis.net/citygml/cityfurniture/1.0" xmlns:bldg="http://www.opengis.net/citygml/building/1.0">
  <gml:name>AC14-FZK-Haus</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="urn:adv:crs:ETRS89_UTM32">
      <gml:lowerCorner srsDimension="3">458877 5438353 -0.2 </gml:lowerCorner>
      <gml:upperCorner srsDimension="3">458889 5438363 6.317669 </gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <core:cityObjectMember>
    <bldg:Building gml:id="UUID_d281adfc-4901-0f52-540b-4cc1a9325f82">
      <gml:description>FZK-Haus (Forschungszentrum Karlsruhe, now KIT), created by Karl-Heinz
        Haefele </gml:description>
      <gml:name>AC14-FZK-Haus</gml:name>
      <core:creationDate>2010-12-01</core:creationDate>
      <bldg:class>1000</bldg:class>
      <bldg:function>1000</bldg:function>
      <bldg:usage>1000</bldg:usage>
      <bldg:yearOfConstruction>2020</bldg:yearOfConstruction>
      <bldg:roofType>1030</bldg:roofType>
      <bldg:measuredHeight uom="m">6.52</bldg:measuredHeight>
      <bldg:storeysAboveGround>2</bldg:storeysAboveGround>
      <bldg:storeysBelowGround>0</bldg:storeysBelowGround>
      <bldg:lod1Solid>
        <gml:Solid>
          <gml:exterior>
            <gml:CompositeSurface>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">458877 5438353 -0.2 458877 5438363 -0.2 458889 5438363 -0.2 458889 5438353 -0.2 458877 5438353 -0.2 </gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">458877 5438353 6.31769 458889 5438353 6.31769 458889 5438363 6.31769 458877 5438363 6.31769 458877 5438353 6.31769 </gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">458877 5438353 -0.2 458877 5438353 6.31769 458877 5438363 6.31769 458877 5438363 -0.2 458877 5438353 -0.2 </gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">458877 5438363 -0.2 458877 5438363 6.31769 458889 5438363 6.31769 458889 5438363 -0.2 458877 5438363 -0.2 </gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">458889 5438363 -0.2 458889 5438363 6.31769 458889 5438353 6.31769 458889 5438353 -0.2 458889 5438363 -0.2 </gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
              <gml:surfaceMember>
                <gml:Polygon>
                  <gml:exterior>
                    <gml:LinearRing>
                      <gml:posList srsDimension="3">458889 5438353 -0.2 458889 5438353 6.31769 458877 5438353 6.31769 458877 5438353 -0.2 458889 5438353 -0.2 </gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:CompositeSurface>
          </gml:exterior>
        </gml:Solid>
      </bldg:lod1Solid>
      <bldg:address> </bldg:address>
    </bldg:Building>
  </core:cityObjectMember>
</core:CityModel>