package de.tub.citydb.db.xlink.resolver;

public enum DBXlinkResolverEnum {
	SURFACE_GEOMETRY,
	TEXCOORDLIST,
	TEXTUREPARAM,
	XLINK_TEXTUREASSOCIATION,
	TEXTURE_IMAGE,
	LIBRARY_OBJECT,
	WORLD_FILE,
	XLINK_DEPRECATED_MATERIAL,
	BASIC,
	GROUP_TO_CITYOBJECT,
}
