package de.tub.citydb.db.xlink;

public enum DBXlinkEnum {
	SURFACE_GEOMETRY,
	LINEAR_RING,
	BASIC,
	TEXTUREPARAM,
	TEXTUREASSOCIATION,
	TEXTURE_FILE,
	LIBRARY_OBJECT,
	DEPRECATED_MATERIAL,
	GROUP_TO_CITYOBJECT
}
