name: docker-build-push-release-alpine

on:
  release:
    types: [released, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v2.4.0
    -
      name: Get release version without v
      id: release_version
      uses: battila7/get-version-action@v2.2.1
    -
      name: Docker login
      id: docker_login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v2.9.0
      with:
        push: true
        file: Dockerfile.alpine
        tags: 3dcitydb/impexp:${{ steps.release_version.outputs.version-without-v }}-alpine,3dcitydb/impexp:latest-alpine
        build-args: |
          IMPEXP_VERSION=${{ steps.release_version.outputs.version }}
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    -
      name: Run container
      run: docker run -t --rm 3dcitydb/impexp:${{ steps.release_version.outputs.version-without-v }}-alpine help | grep -i -E "Usage:"
