name: docker-build-edge

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v2
    -
      name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: 3dcitydb/impexp-test:edge
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    -
      name: Run container
      run: docker run -t --rm 3dcitydb/impexp-test:edge help | grep -i -E "Usage:"
