name: impexp-build

on:
  push:
    branches:
    - master
  pull_request:

env:
  GPR_USERNAME: ${{ vars.GPR_USERNAME }}
  GPR_TOKEN: ${{ vars.GPR_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
